---
- hosts: all
  tasks:
  - name: ensure basic packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release
      - net-tools
      - htop
      - vim
      - lsof
  - name: Create a /www directory if it does not exist
    file:
      path: /www/
      state: directory

