---
- hosts: all
  tasks:
  - name: ensure basic packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release
      - net-tools
      - htop
      - vim
      - lsof
